[package]
name = "blog_os"
version = "0.1.0"
authors = ["Author Name <author@example.com>"]
edition = "2018"

[dependencies]
bootloader = "0.9.8"
volatile = "0.2.7"
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
